specfile_path: zezere.spec
upstream_tag_template: 'v{version}'
jobs:
  - job: copr_build
    trigger: pull_request
    targets:
    - fedora-all
  
  - job: sync_from_downstream
    trigger: commit
  - job: propose_downstream
    trigger: release
    metadata:
      dist_git_branches: fedora-all
  - job: tests
    trigger: pull_request
    metadata:
      targets:
        - fedora-all
